### ISSUE TITLE
Conf tenant.yaml not work

### ISSUE THREAD

**Issue by cbouisson-csgroup** [CS-SI/SafeScale#106]
Conf tenant.yaml not work

Safescaled version: 21.05.0-rc3, build 4e6134c0f0f603869799a4f0e0b1b83c4315c8c4 (2021/10/04-17:04)

**Comment by vplanche-cssi** [comment]
Hum... What is not working exactly ?

**Comment by wruffine-csgroup** [comment]
"invalid configuration file. A tenant has no 'name' entry"

At line 656 of lib/server/iaas/factory.go, the tenant is casted in a `map[string]interface{}` format. I think in the yaml file, "name", "client", "identity" and others are not considered a string. From what I have gathered, yaml files are usually parsed in a `map[interface{}]interface{}`format.

**Comment by vplanche-cssi** [comment]
For me, the tenant does not have a **_name_** entry, as reported.

Could you share the tenant here (with credentials obfuscated), please ?

**Comment by wruffine-csgroup** [comment]
```yaml
tenants:
- name: xxxxxxxx
  client: flexibleengine
  identity:
    Username: xxxxxxx
    Password: xxxxxxx
    DomainName: OCB0005298
  compute:
    ProjectID: xxxxxxxxx
    Region: eu-west-0
    AvailabilityZone: eu-west-0b
    DefaultImage: 'Ubuntu 20.04'
    Scannable: true
    WhitelistTemplateRegexp: ".*s3.*"
  network:
    VPCName: xxxxxxxxxx
    VPCCIDR: 192.168.0.0/16
  objectstorage:
    Type: s3
    Endpoint: xxxxxxx
    AccessKey: xxxxxx
    SecretKey: xxxxx
  metadata:
    MetadataBucketName: xxxxxx
```
But this following tenants.yaml file also raises the same issue :
```yaml
tenants:
- name: mytest
```
