### ISSUE TITLE
Cannot create BOH cluster on OVH

### ISSUE THREAD

**Issue by edepremare-cs** [CS-SI/SafeScale#426]
Hello,
I have an issue on the latest v22.06.1 release on the OVH cloud provider.

**Current behaviour**

This command:
```bash
safescale  cluster create --complexity small --flavor BOH  --disable remotedesktop --disable reverseproxy --os Ubuntu 20.04"'  --master-sizing 'cpu=4,ram>1,disk>1' --node-sizing 'cpu=4,ram>1,disk>1,count=0' --gw-sizing 'cpu=4,ram>1,disk>1' rs-test
```
Gives:
```bash
{"error":{"exitcode":1,"message":"cannot create clusterfbc97622-830d-4c5a-86e7-b426748a7184/cluster/rs-test/create+/masters: [Cluster rs-test] failed to create master(s): fbc97622-830d-4c5a-86e7-b426748a7184/cluster/rs-test/create+/masters+/host/1/create: failed to execute install phase 'netsec' on Host 'rs-test-master-1': PROVISIONING_ERROR: 214, DNS NOT ready after being configured"},"result":null,"status":"failure"}
```

My tenant file:
```yaml
tenants:
  - name: ovh-test
    client: ovh
    identity:
      OpenstackID: XXXXXXXXX
      OpenstackPassword: XXXXXXXXXX
    compute:
      Region: SBG5
      ProjectID: XXXXXXXXXXX
      ProjectName: 'XXXXXXXXXX'
      DefaultImage: 'Ubuntu 20.04'
      WhitelistTemplateRegexp: "d2.*"
      DNS: '1.1.1.1,1.0.0.1'
    objectstorage:
      AuthURL: https://auth.cloud.ovh.net/v3
      Type: s3
      Region: SBG
      Endpoint: 'https://s3.sbg.cloud.ovh.net'
      AccessKey: XXXXXXXXXX
      SecretKey: XXXXXXXXXXXX
    metadata:
      MetadataBucketName: test-safescale
```

I could access the gateway use `safescale ssh connect` command, but not the master, which I could only access using the provider's console because the ssh private key were not working.
The master node has the right ip route pointing to the gateway but has no access to any other machine, specially not to any DNS server.

** Expected behaviour**
The cluster should be created and working.

**Steps to reproduce**
Try to create a cluster.
